# Generated by Django 5.2 on 2025-05-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDeath',
            fields=[
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.child')),
                ('date_of_death', models.DateField(verbose_name='date of death')),
            ],
            options={
                'verbose_name': 'child death',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
            ],
            options={
                'verbose_name': 'employee',
            },
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'child', 'verbose_name_plural': 'children'},
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='patronymic'),
        ),
        migrations.CreateModel(
            name='ChildAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(verbose_name='date of admission')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'child admission',
                'verbose_name_plural': 'child admissions',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='working rate')),
                ('position_name', models.CharField(max_length=100, verbose_name='Должности')),
                ('report_category', models.CharField(choices=[('1', 'Врач'), ('2', 'Средний медицинский персонал'), ('3', 'Младший медицинский персонал'), ('4', 'Провизор'), ('5', 'Фармацевт'), ('6', 'Педагогический персонал'), ('7', 'Специалисты с высшим не медицинским образованием'), ('8', 'Прочий персонал')])),
                ('start_date_of_employment', models.DateField(verbose_name='start date of employment')),
                ('end_date_of_employment', models.DateField(blank=True, null=True, verbose_name='end date of employment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'verbose_name': 'employment',
            },
        ),
    ]
