# Generated by Django 5.2 on 2025-05-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDeath',
            fields=[
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.child')),
                ('date_of_death', models.DateField(verbose_name='дата смерти')),
            ],
            options={
                'verbose_name': 'смертность',
                'verbose_name_plural': 'смертность',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
            ],
            options={
                'verbose_name': 'сотрудники',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'child', 'verbose_name_plural': 'children'},
        ),
        migrations.AddField(
            model_name='child',
            name='disability_category',
            field=models.IntegerField(default=0, verbose_name='категория инвалидности'),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='patronymic'),
        ),
        migrations.CreateModel(
            name='ChildAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(verbose_name='дата поступления')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'child admission',
                'verbose_name_plural': 'child admissions',
            },
        ),
        migrations.CreateModel(
            name='ChildAdopted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_adoption', models.DateField(verbose_name='Дата усыновления')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'усыновленный ребёнок',
                'verbose_name_plural': 'усыновленные дети',
            },
        ),
        migrations.CreateModel(
            name='AdoptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childadopted')),
            ],
            options={
                'verbose_name': 'приемные родители',
                'verbose_name_plural': 'приемные родители',
            },
        ),
        migrations.CreateModel(
            name='ChildCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_adoption', models.DateField(verbose_name='Дата взятия в приемную семью или под опекунство')),
                ('care_type', models.CharField(choices=[('1', 'Взято под опеку'), ('2', 'Взято приемной семьей')], verbose_name='Тип попечительства')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'попечительство',
                'verbose_name_plural': 'попечительство',
            },
        ),
        migrations.CreateModel(
            name='ChildRepatriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_repatriation', models.DateField(verbose_name='дата репатриации')),
                ('country', models.CharField(max_length=100, verbose_name='страна репатриации')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'репатриация',
                'verbose_name_plural': 'репатриация',
            },
        ),
        migrations.CreateModel(
            name='ChildReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_adoption', models.DateField(verbose_name='Дата взятия родителями')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'ребёнок, взятый родителями',
                'verbose_name_plural': 'Дети, взятые родителями',
            },
        ),
        migrations.CreateModel(
            name='ChildParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childreturned')),
            ],
            options={
                'verbose_name': 'родитель',
                'verbose_name_plural': 'родители',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='working rate')),
                ('position_name', models.CharField(max_length=100, verbose_name='Должности')),
                ('report_category', models.CharField(choices=[('1', 'Врач'), ('2', 'Средний медицинский персонал'), ('3', 'Младший медицинский персонал'), ('4', 'Провизор'), ('5', 'Фармацевт'), ('6', 'Педагогический персонал'), ('7', 'Специалисты с высшим не медицинским образованием'), ('8', 'Прочий персонал')])),
                ('start_date_of_employment', models.DateField(verbose_name='start date of employment')),
                ('end_date_of_employment', models.DateField(blank=True, null=True, verbose_name='end date of employment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'verbose_name': 'трудоустройство',
                'verbose_name_plural': 'трудоустройство',
            },
        ),
        migrations.CreateModel(
            name='InternationalAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_adoption', models.DateField(verbose_name='дата усыновления')),
                ('country', models.CharField(max_length=100, verbose_name='страна переезда')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'международное усыновление',
                'verbose_name_plural': 'международное усыновление',
            },
        ),
        migrations.CreateModel(
            name='SicknessRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(max_length=100, verbose_name='код диагноза по МКБ')),
                ('date_of_appointment', models.DateField(verbose_name='дата постановления диагноза')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'заболеваемость',
                'verbose_name_plural': 'заболеваемости',
            },
        ),
        migrations.CreateModel(
            name='TransferByCertainAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transfer', models.DateField(verbose_name='дата перевода в учреждение')),
                ('type', models.CharField(choices=[('1', 'Образовательная организация'), ('2', 'Организация социальной защиты населения')])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'Перевод в учреждения по достижению определенного возраста',
                'verbose_name_plural': 'Перевод в учреждения по достижению определенного возраста',
            },
        ),
        migrations.CreateModel(
            name='TransferToTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transfer', models.DateField(verbose_name='дата перевода')),
                ('organization', models.CharField(max_length=100, verbose_name='название организации')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'перевод в медицинские организации',
                'verbose_name_plural': 'перевод в медицинские организации',
            },
        ),
    ]
