# Generated by Django 5.2 on 2025-05-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_childdeath_employee_alter_child_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=100, verbose_name='местоположение')),
                ('count_of_seats', models.IntegerField(default=0, verbose_name='количество мест')),
            ],
            options={
                'verbose_name': 'информация о доме ребенка',
                'verbose_name_plural': 'информация о доме ребенка',
            },
        ),
        migrations.CreateModel(
            name='WorkWithContingents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(max_length=100, verbose_name='код диагноза по МКБ')),
                ('indicator_name', models.CharField(max_length=100, verbose_name='наименование показателей')),
            ],
            options={
                'verbose_name': 'работа с контингентами',
                'verbose_name_plural': 'работа с контингентами',
            },
        ),
        migrations.AddField(
            model_name='childadmission',
            name='admission_type',
            field=models.CharField(choices=[('1', 'Сирота'), ('2', 'Оставшийся без попечения родителей')], default='1', verbose_name='причина поступления'),
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_checkup', models.DateField(verbose_name='дата профилактического осмотра')),
                ('diagnosis', models.CharField(max_length=100, verbose_name='диагноз')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'профилактические осмотры',
                'verbose_name_plural': 'профилактические осмотры',
            },
        ),
        migrations.CreateModel(
            name='ChildSickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_diagnosis', models.DateField(verbose_name='дата постановления диагноза')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('icd_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workwithcontingents')),
            ],
            options={
                'verbose_name': 'заболеваемость',
                'verbose_name_plural': 'заболеваемости',
            },
        ),
        migrations.DeleteModel(
            name='SicknessRate',
        ),
    ]
