# Generated by Django 5.2 on 2025-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orphanage_workwithcontingents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childsickness',
            name='icd_code',
            field=models.CharField(max_length=100, verbose_name='код диагноза по МКБ'),
        ),
        migrations.RemoveField(
            model_name='internationaladoption',
            name='country',
        ),
        migrations.RemoveField(
            model_name='internationaladoption',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='internationaladoption',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='internationaladoption',
            name='patronymic',
        ),
        migrations.DeleteModel(
            name='WorkWithContingents',
        ),
    ]
