# Generated by Django 5.2 on 2025-05-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_childsickness_icd_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='position_name',
        ),
    ]
