# Generated by Django 5.2 on 2025-05-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employment_position_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionparent',
            options={'verbose_name': 'приемного родителя', 'verbose_name_plural': 'приемные родители'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'ребёнка', 'verbose_name_plural': 'дети'},
        ),
        migrations.AlterModelOptions(
            name='childadmission',
            options={'verbose_name': 'поступление ребёнка', 'verbose_name_plural': 'поступление детей'},
        ),
        migrations.AlterModelOptions(
            name='childadopted',
            options={'verbose_name': 'усыновленного ребёнка', 'verbose_name_plural': 'усыновленные дети'},
        ),
        migrations.AlterModelOptions(
            name='childcare',
            options={'verbose_name': 'попечительство', 'verbose_name_plural': 'попечительства'},
        ),
        migrations.AlterModelOptions(
            name='childparent',
            options={'verbose_name': 'родителя', 'verbose_name_plural': 'родители'},
        ),
        migrations.AlterModelOptions(
            name='childrepatriation',
            options={'verbose_name': 'репатриацию', 'verbose_name_plural': 'репатриации'},
        ),
        migrations.AlterModelOptions(
            name='childreturned',
            options={'verbose_name': 'ребёнка, взятого родителями', 'verbose_name_plural': 'дети, взятые родителями'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудника', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'verbose_name': 'трудоустройство', 'verbose_name_plural': 'трудоустройства'},
        ),
        migrations.AlterModelOptions(
            name='internationaladoption',
            options={'verbose_name': 'международное усыновление', 'verbose_name_plural': 'международные усыновления'},
        ),
        migrations.AlterModelOptions(
            name='transferbycertainage',
            options={'verbose_name': 'перевод в учреждения по достижению определенного возраста', 'verbose_name_plural': 'переводы в учреждения по достижению определенного возраста'},
        ),
        migrations.RemoveField(
            model_name='childrepatriation',
            name='country',
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='adoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childadopted', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='child',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='childadmission',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childadopted',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childadopted',
            name='date_of_adoption',
            field=models.DateField(verbose_name='дата усыновления'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='care_type',
            field=models.CharField(choices=[('1', 'Взято под опеку'), ('2', 'Взято приемной семьей')], verbose_name='тип попечительства'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='date_of_adoption',
            field=models.DateField(verbose_name='дата взятия в приемную семью или под опекунство'),
        ),
        migrations.AlterField(
            model_name='childdeath',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='returned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childreturned', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childrepatriation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childreturned',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='childreturned',
            name='date_of_adoption',
            field=models.DateField(verbose_name='дата взятия родителями'),
        ),
        migrations.AlterField(
            model_name='childsickness',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ставка'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='report_category',
            field=models.CharField(choices=[('1', 'Врач'), ('2', 'Средний медицинский персонал'), ('3', 'Младший медицинский персонал'), ('4', 'Провизор'), ('5', 'Фармацевт'), ('6', 'Педагогический персонал'), ('7', 'Специалисты с высшим не медицинским образованием'), ('8', 'Прочий персонал')], verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date_of_employment',
            field=models.DateField(verbose_name='дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='internationaladoption',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='transferbycertainage',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
        migrations.AlterField(
            model_name='transfertotreatment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='ребёнок'),
        ),
    ]
