"""
Django settings for orphanage project.

Generated by 'django-commands startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-lipla5v9+ve2gf#s@x_xi1tb32n)hquz#ozzkqj2suc8g$$2=g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', True)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold theme
    # see https://unfoldadmin.com/docs/installation/quickstart/
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orphanage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orphanage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME', 'db'),
        "USER": os.environ.get('DB_USER', 'db'),
        "PASSWORD": os.environ.get('DB_USER_PASSWORD', 'db'),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# UNFOLD ADMIN SETTINGS
# See https://unfoldadmin.com/docs/configuration/settings/
# Icons here: https://fonts.google.com/icons
UNFOLD = {
    "SITE_TITLE": "Дом Ребёнка",
    "SITE_HEADER": "Дом Ребёнка",
    "SITE_SYMBOL": "house",  # symbol from icon set https://fonts.google.com/icons
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Отчётность",
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Отчёт по форме №41",
                        "icon": "article",
                        "link": reverse_lazy("report_summary"),

                    },
                    {
                        #"title": "Отчёт 1000 - Дома ребёнка",
                        "title": "Дома ребёнка",
                        "icon": "article",
                        "link": reverse_lazy("report_1000"),
                    },
                    {
                        #"title": "Отчёт 2100 - Штаты организации",
                        "title": "Штаты организации",
                        "icon": "article",
                        "link": reverse_lazy("report_2100"),
                    },
                    {
                        #"title": "Отчёт 2120 - Контингенты дома ребёнка",
                        "title": "Контингенты дома ребёнка",
                        "icon": "article",
                        "link": reverse_lazy("report_2120"),
                    },
                    {
                        #"title": "Отчёт 2140 - Движение контингентов дома ребёнка",
                        "title": "Движение контингентов",
                        "icon": "article",
                        "link": reverse_lazy("report_2140"),
                    },
                    {
                        #"title": "Отчёт 2145 - Профилактические осмотры детей и их результаты",
                        "title": "Профилактические осмотры",
                        "icon": "article",
                        "link": reverse_lazy("report_2145"),
                    },
                    {
                        #"title": "Отчёт 2146 - Работа с контингентами детей, находящихся в доме ребёнка",
                        "title": "Работа с контингентами детей",
                        "icon": "article",
                        "link": reverse_lazy("report_2146"),
                    },
                    {
                        #"title": "Отчёт 2150 - Заболеваемость детей",
                        "title": "Заболеваемость детей",
                        "icon": "article",
                        "link": reverse_lazy("report_2150"),
                    },
                ]
            },
            {
                "title": "Загрузка",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Профилактика (2145)",
                        "icon": "docs",
                        "link": reverse_lazy("upload_2145")
                    },
                    {
                        "title": "Работа с контингентами (2146)",
                        "icon": "docs",
                        "link": reverse_lazy("upload_2146")
                    },
                ]
            },
            {
                "title": "Контингент",
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Контингент",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_child_changelist")
                    },
                    {
                        "title": "Поступление контингента",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_childadmission_changelist")
                    },
                    {
                        "title": "Дети, отданные под опеку или в приемную семью",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_childcare_changelist")
                    },
                    {
                        "title": "Дети, взятые родителями",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_childreturned_changelist")
                    },
                    {
                        "title": "Переведенные в медицинские организации",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_transfertotreatment_changelist")
                    },
                    {
                        "title": "Усыновленные дети",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_childadopted_changelist")
                    },
                    {
                        "title": "Перевод по достижению возраста",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_transferbycertainage_changelist")
                    },
                    {
                        "title": "Репатриация",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_childrepatriation_changelist")
                    },
                    {
                        "title": "Международное усыновление",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_internationaladoption_changelist")
                    },
                ]
            },
            {
                "title": "Сотрудники",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Сотрудники",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_employee_changelist")
                    },
                    {
                        "title": "Трудоустройство",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_employment_changelist")
                    },
                    {
                        "title": "Штатное расписание",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_plannedrates_changelist")
                    },
                ]
            },
            {
                "title": "Заболевания",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Заболеваемость детей",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_childsickness_changelist")
                    },
                    {
                        "title": "Профилактика детей",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_checkup_changelist")
                    },
                ]
            },
            {
                "title": "Общая информация",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Сведения о домах",
                        "icon": "docs",
                        "link": reverse_lazy("admin:core_orphanage_changelist")
                    },
                ]
            },
            {
                "title": "Пользователи и группы",
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": "Пользователи",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Группы",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ]
            },
        ]
    }
}

# UNFOLD = {
#     "SITE_TITLE": "Custom suffix in <title> tag",
#     "SITE_HEADER": "Appears in sidebar at the top",
#     "SITE_SUBHEADER": "Appears under SITE_HEADER",
#     "SITE_DROPDOWN": [
#         {
#             "icon": "diamond",
#             "title": _("My site"),
#             "link": "https://example.com",
#         },
#         # ...
#     ],
#     "SITE_URL": "/",
#     # "SITE_ICON": lambda request: static("icon.svg"),  # both modes, optimise for 32px height
#     "SITE_ICON": {
#         "light": lambda request: static("icon-light.svg"),  # light mode
#         "dark": lambda request: static("icon-dark.svg"),  # dark mode
#     },
#     # "SITE_LOGO": lambda request: static("logo.svg"),  # both modes, optimise for 32px height
#     "SITE_LOGO": {
#         "light": lambda request: static("logo-light.svg"),  # light mode
#         "dark": lambda request: static("logo-dark.svg"),  # dark mode
#     },
#     "SITE_SYMBOL": "speed",  # symbol from icon set
#     "SITE_FAVICONS": [
#         {
#             "rel": "icon",
#             "sizes": "32x32",
#             "type": "image/svg+xml",
#             "href": lambda request: static("favicon.svg"),
#         },
#     ],
#     "SHOW_HISTORY": True, # show/hide "History" button, default: True
#     "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
#     "SHOW_BACK_BUTTON": False, # show/hide "Back" button on changeform in header, default: False
#     "ENVIRONMENT": "sample_app.environment_callback", # environment name in header
#     "ENVIRONMENT_TITLE_PREFIX": "sample_app.environment_title_prefix_callback", # environment name prefix in title tag
#     "DASHBOARD_CALLBACK": "sample_app.dashboard_callback",
#     "THEME": "dark", # Force theme: "dark" or "light". Will disable theme switcher
#     "LOGIN": {
#         "image": lambda request: static("sample/login-bg.jpg"),
#         "redirect_after": lambda request: reverse_lazy("admin:APP_MODEL_changelist"),
#     },
#     "STYLES": [
#         lambda request: static("css/style.css"),
#     ],
#     "SCRIPTS": [
#         lambda request: static("js/script.js"),
#     ],
#     "BORDER_RADIUS": "6px",
#     "COLORS": {
#         "base": {
#             "50": "249 250 251",
#             "100": "243 244 246",
#             "200": "229 231 235",
#             "300": "209 213 219",
#             "400": "156 163 175",
#             "500": "107 114 128",
#             "600": "75 85 99",
#             "700": "55 65 81",
#             "800": "31 41 55",
#             "900": "17 24 39",
#             "950": "3 7 18",
#         },
#         "primary": {
#             "50": "250 245 255",
#             "100": "243 232 255",
#             "200": "233 213 255",
#             "300": "216 180 254",
#             "400": "192 132 252",
#             "500": "168 85 247",
#             "600": "147 51 234",
#             "700": "126 34 206",
#             "800": "107 33 168",
#             "900": "88 28 135",
#             "950": "59 7 100",
#         },
#         "font": {
#             "subtle-light": "var(--color-base-500)",  # text-base-500
#             "subtle-dark": "var(--color-base-400)",  # text-base-400
#             "default-light": "var(--color-base-600)",  # text-base-600
#             "default-dark": "var(--color-base-300)",  # text-base-300
#             "important-light": "var(--color-base-900)",  # text-base-900
#             "important-dark": "var(--color-base-100)",  # text-base-100
#         },
#     },
#     "EXTENSIONS": {
#         "modeltranslation": {
#             "flags": {
#                 "en": "🇬🇧",
#                 "fr": "🇫🇷",
#                 "nl": "🇧🇪",
#             },
#         },
#     },
#     "SIDEBAR": {
#         "show_search": False,  # Search in applications and models names
#         "show_all_applications": False,  # Dropdown with all applications and models
#         "navigation": [
#             {
#                 "title": _("Navigation"),
#                 "separator": True,  # Top border
#                 "collapsible": True,  # Collapsible group of links
#                 "items": [
#                     {
#                         "title": _("Dashboard"),
#                         "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
#                         "link": reverse_lazy("admin:index"),
#                         "badge": "sample_app.badge_callback",
#                         "permission": lambda request: request.user.is_superuser,
#                     },
#                     {
#                         "title": _("Users"),
#                         "icon": "people",
#                         "link": reverse_lazy("admin:auth_user_changelist"),
#                     },
#                 ],
#             },
#         ],
#     },
#     "TABS": [
#         {
#             "models": [
#                 "app_label.model_name_in_lowercase",
#             ],
#             "items": [
#                 {
#                     "title": _("Your custom title"),
#                     "link": reverse_lazy("admin:app_label_model_name_changelist"),
#                     "permission": "sample_app.permission_callback",
#                 },
#             ],
#         },
#     ],
# }
